name: auto-merge

on:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'  # every day at midnight

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.dependabot_token }}
